### ISSUE TITLE
Création de page de recherche

### ISSUE THREAD

**Issue by drimov** [drimov/ProjetReact#22]
On veux pouvoir faire des recherche au niveaux des recettes:
- par ingrédient
- par nom
- par catégorie

**Comment by drimov** [comment]
Pour les nouvelles directives:
- un Highlight comme celui-ci : https://dribbble.com/shots/22211424-Food-Website-Design
- un Last receipes comme l'exemple déjà donné
- une barre de recherche au premier plan ou a ajouter dans la navbar ? (faudra discuter)
- pour un présentation d'un plat:
  - exemple 1 : https://dribbble.com/shots/21398554-Food-Recipe-Listing-Landing-Page-UI-design
  - exemple 2 : https://dribbble.com/shots/20994352-Chef-Website-Design
- Faire les choix ou mix nécessaire (on peux en discuter)

**Comment by drimov** [comment]
découpage :

Header: 
![image](https://github.com/drimov/ProjetReact/assets/7766411/8fde24d2-123a-41fc-8e75-fa4e2efb52bf)

tags:
![image](https://github.com/drimov/ProjetReact/assets/7766411/64201db1-bf79-48ed-8bc5-76b9a00930ff)


affiache par défaut:
higlight : 
![image](https://github.com/drimov/ProjetReact/assets/7766411/1214d9c3-9c2e-4b1b-bc4c-d048ecea821e)

last receipes : 
![image](https://github.com/drimov/ProjetReact/assets/7766411/9776e5e0-956d-4252-9963-042636602d1e)

**Comment by BambaThiam** [comment]
Intégré
