### ISSUE TITLE
Formulaire de connexion

### ISSUE THREAD

**Issue by drimov** [drimov/ProjetReact#27]
- Pour créer un formulaire avec TS et react-hook-form :
   - installer @hookform/resolvers pour faire fonctionner zod et react-hook-form
   - créer un schéma de donnée
   - extraire le type (z.infer<typeof nom_du_shema>)
   - créer le form (le visuel)
   - utiliser react-hook-form pour valider ou non le formulaire
- aide : https://articles.wesionary.team/react-hook-form-schema-validation-using-zod-80d406e22cd8

**Comment by ValM34** [comment]
J'ai implémenté le formulaire de connexion, normalement tout y est. A noter que pour que le design fonctionne correctement il faudra attendre la suppression de src/index.css sur la branche dev.

**Comment by ValM34** [comment]
Il manque juste 2 erreurs esLint à corriger.
