### ISSUE TITLE
Mise en place de React-Query

### ISSUE THREAD

**Issue by drimov** [drimov/ProjetReact#3]
Même chose que React- router, il faut le configurer pour le projet : 
- https://tanstack.com/query/latest/docs/react/installation
- https://www.notion.so/React-Query-d8e309bec09b439e85e632f5be467b17?pvs=4

**Comment by BambaThiam** [comment]
Je crée une branche du même nom à partir de la branche Dev

**Comment by drimov** [comment]
oui c'est ça
